apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: railsapp-deployment
  namespace: default
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 50
    type: Resource
  minReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: railsapp-deployment
